# Name that will appear in copy throughout the app and next to the icon.
name: Bigscreen

# URL string to show in the web address text field by default. Use null if none.
url: "https://www.google.com/"

